language: node_js
sudo: required
dist: xenial 
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- --require babel-register -R spec
  - ./node_modules/.bin/codecov
  - npm test